# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.grpc.process_service import process_service_pb2 as src_dot_grpc_dot_process__service_dot_process__service__pb2

GRPC_GENERATED_VERSION = '1.65.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/grpc/process_service/process_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ProcessServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.start_learning_process = channel.unary_unary(
                '/processservice.ProcessService/start_learning_process',
                request_serializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.StartLearningProcessRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.LearningSetDTO.FromString,
                _registered_method=True)
        self.get_learning_set = channel.unary_unary(
                '/processservice.ProcessService/get_learning_set',
                request_serializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.GetLearningSetRequest.SerializeToString,
                response_deserializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.LearningSetDTO.FromString,
                _registered_method=True)
        self.update_learning_progress = channel.unary_unary(
                '/processservice.ProcessService/update_learning_progress',
                request_serializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.UpdateLearningProgressRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.add_learning_set_to_cash = channel.unary_unary(
                '/processservice.ProcessService/add_learning_set_to_cash',
                request_serializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.LearningSetDTO.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ProcessServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def start_learning_process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_learning_set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_learning_progress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_learning_set_to_cash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'start_learning_process': grpc.unary_unary_rpc_method_handler(
                    servicer.start_learning_process,
                    request_deserializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.StartLearningProcessRequest.FromString,
                    response_serializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.LearningSetDTO.SerializeToString,
            ),
            'get_learning_set': grpc.unary_unary_rpc_method_handler(
                    servicer.get_learning_set,
                    request_deserializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.GetLearningSetRequest.FromString,
                    response_serializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.LearningSetDTO.SerializeToString,
            ),
            'update_learning_progress': grpc.unary_unary_rpc_method_handler(
                    servicer.update_learning_progress,
                    request_deserializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.UpdateLearningProgressRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'add_learning_set_to_cash': grpc.unary_unary_rpc_method_handler(
                    servicer.add_learning_set_to_cash,
                    request_deserializer=src_dot_grpc_dot_process__service_dot_process__service__pb2.LearningSetDTO.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'processservice.ProcessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('processservice.ProcessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def start_learning_process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processservice.ProcessService/start_learning_process',
            src_dot_grpc_dot_process__service_dot_process__service__pb2.StartLearningProcessRequest.SerializeToString,
            src_dot_grpc_dot_process__service_dot_process__service__pb2.LearningSetDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_learning_set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processservice.ProcessService/get_learning_set',
            src_dot_grpc_dot_process__service_dot_process__service__pb2.GetLearningSetRequest.SerializeToString,
            src_dot_grpc_dot_process__service_dot_process__service__pb2.LearningSetDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_learning_progress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processservice.ProcessService/update_learning_progress',
            src_dot_grpc_dot_process__service_dot_process__service__pb2.UpdateLearningProgressRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_learning_set_to_cash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processservice.ProcessService/add_learning_set_to_cash',
            src_dot_grpc_dot_process__service_dot_process__service__pb2.LearningSetDTO.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
